### ISSUE TITLE
hello . great tool 

### ISSUE THREAD

**Issue by saberzaid** [som3canadian/Some-Tools#1]
hello there

great tool and will save time 

i installed it and i sow the bin directory been created 

but what next now? im using zsh shell with .zplugin features 

how i can access all the tools from the shell it self without the need of going to the directory and run the tool

**Comment by som3canadian** [comment]
Thanks for reaching out @saberzaid 
After the setup process, you should be able to list the tools with. You can check your path before to be sure the installation is completed:
```bash
# check your path
$ echo $PATH
# list tools
$ ./sometools.sh list
```

At this point you can install any tools you want. Tools are not installed by default, you have to install the one you want.
For the running the tools part. All the tools "accessible from anywhere" will be symlink in the `bin` directory (so you can list the bin directory). Not all the tools have been setup this way. But for example, a tool like evil-winrm will be. You can modify `install-tool.sh` if you want to modify the installation process of a tool or suggest which one and I will take it in consideration.

Privilege Escalation scripts will be placed in `bin/PrivEsc-Lin` or `bin/PrivEsc-Win`, so it makes it easier to transfer files when you setup a python server (or any others ways).

Let me know if you still have questions.

**Comment by saberzaid** [comment]
Hi again 

Thanks for your replay and respond

Yes i already setup and already install all the tools using install all option 

Seen the bin folder been created inside some-tools folder and also all the tools been downloaded and install and i can see the folder of each tool and i sow the files of the tools 

But i cant seems to run the tools from any location within my zsh terminal 

Some tool run from anywhere like evil-winrm but i dont know if this comes with kali or no 

Some tools not 

For example spareRat not run from any location , i was just doing a test to know if its working 


Thanks again

**Comment by som3canadian** [comment]
Evil-winrm doesnt come by default in Kali. So my first question is: are you able to use evil-winrm "from anywhere" ?

For SirepRAT, this tool it is NOT symlink in the bin dir by default. Why ? Because in my opinion it's not a "day to day" tool but still enough important to put it in Some-Tools. If you want to run it from anywhere, you will have to symlink manually.

Make sense ?

**Comment by saberzaid** [comment]
I got it 

Yes , so all is well and work Just only few tools as they are not symlink 

Is there away to know the non symlink tools list 

Anyhow very thank you for this one of the best i discover this month

**Comment by som3canadian** [comment]
No but it's a good idea. Will work on it. 🔥

Thanks a lot @saberzaid ❤️
